pipeline:
  hugo:
    image: cbrgm/drone-hugo:latest
    output: public
    validate: true

  minify:
    image: mysocialobservations/docker-tdewolff-minify
    commands:
      - >-
        minify --recursive --verbose --match=\.*.js$ --type=js --output public/ public/
      - >-
        minify --recursive --verbose --match=\.*.css$ --type=css --output public/ public/
      - >-
        minify --recursive --verbose --match=\.*.html$ --type=html --output public/ public/

  publish-docker:
    image: plugins/docker
    repo: jtreminio/jtreminio.com
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
    dockerfile: ./build/Dockerfile
    context: ./

  deploy:
    image: appleboy/drone-ssh
    host: jtreminio.com
    username: root
    port: 22
    secrets: [ ssh_key ]
    script:
      - docker image pull jtreminio/jtreminio.com
      - docker container rm -f jtreminio_com
      - >-
        docker container run -d --name jtreminio_com \
          --label "traefik.backend=jtreminio_com" \
          --label "traefik.docker.network=traefik_webgateway" \
          --label "traefik.frontend.rule=Host:jtreminio.com" \
          --label "traefik.port=80" \
          --network traefik_webgateway \
          --restart always \
          jtreminio/jtreminio.com
