pipeline:
  hugo:
    image: cbrgm/drone-hugo:latest
    output: public
    validate: true

  minify:
    image: node:9-alpine
    commands:
      - npm install
      - npm run build

  publish-docker:
    image: plugins/docker
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: jtreminio/jtreminio.com
    tags:
      - latest
    dockerfile: ./Dockerfile
    context: .
