pipeline:
  hugo:
    image: cbrgm/drone-hugo:latest
    output: public
    validate: true

  minify:
    image: node:9-alpine
    commands:
      - npm install
      - npm run build

  publish-docker:
    image: plugins/docker
    repo: jtreminio/jtreminio.com
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
    dockerfile: ./Dockerfile
    context: .
